version: "3.8"

services:
  jellyfin:
    container_name: jellyfin
    image: jellyfin/jellyfin
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/New_York
    volumes:
      - /docker/jellyfin:/config
      - /mnt/raid1/Jellyfin:/data/jellyfin
    ports:
      - 8074:8096
    restart: unless-stopped

  jellyseerr:
    image: fallenbagel/jellyseerr:latest
    container_name: jellyseerr
    restart: unless-stopped
    ports:
      - 8075:5055
    volumes:
      - /docker/jellyseerr/config:/app/config
      - /mnt/raid1/Jellyfin:/jellyfin
